name: HelloPlugin
main: com.wellintlabs.hello.MyFirstPlugin
version: 1.5
commands:
    hello:
        description: It replies to player with greeting!
permissions:
    hello.reload:
        description: User-friendly description
        default: op